Repository wirecard/magento2-ee, pull requests merged in 2020-04, with the labels that each got.

#394 Tpwdcee 6280 feature
  Block/Checkout/CreditCardThreeDForm.php
  Controller/Frontend/Callback.php
  Controller/Frontend/Redirect.php
  Gateway/Response/ResponseHandler.php
  Test/Unit/Controller/Frontend/RedirectTest.php
  Test/Unit/Gateway/Response/ResponseHandlerUTest.php
  Test/Unit/Model/Ui/TokenUiComponentProviderUTest.php
  _TERMS_OF_USE
  composer.json
  i18n/de_DE.csv
  view/frontend/layout/wirecard_elasticengine_frontend_callback.xml
  view/frontend/layout/wirecard_elasticengine_frontend_sepamandate.xml
  view/frontend/templates/creditcardthreedform.phtml
  view/frontend/web/js/view/payment/method-renderer/constants.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
  view/frontend/web/js/view/payment/seamless-vault-enabler.js
Labels: ready for review

#399 Adjust creation date.
  Gateway/Request/AccountInfoFactory.php
Labels: ready for review

#397 Tpwdcee 5953 feature
  Gateway/Command/WirecardRefundCommand.php
  Gateway/Request/BasketFactory.php
  Test/Unit/Gateway/Request/BasketFactoryUTest.php
Labels: ready for review

#401 Tpwdcee 5465 feature Alipay logo
  view/frontend/web/images/alipayxborder.png
Labels: ready for merge

#404 Tpwdcee 6279 feature
  Controller/Frontend/Creditcard.php
  Gateway/Helper/AccountHolderMapper.php
  Test/Unit/Controller/Frontend/CreditcardTest.php
  view/frontend/web/js/view/payment/method-renderer/constants.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
Labels: ready for merge

#403 Tpwdcee 6214 feature
  Controller/Frontend/Sepamandate.php
  Test/Unit/Controller/Frontend/SepamandateUTest.php
  view/frontend/layout/wirecard_elasticengine_frontend_callback.xml
  view/frontend/layout/wirecard_elasticengine_frontend_sepamandate.xml
Labels: ready for merge

#412 Refactor javascript
  Gateway/Request/AccountInfoFactory.php
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
  view/frontend/web/js/view/payment/seamless-vault-enabler.js
Labels: ready for merge

#406 Adjust payment icons view.
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/css/main.css
  view/frontend/web/images/alipayxborder.png
  view/frontend/web/images/creditcard.png
  view/frontend/web/images/giropay.png
  view/frontend/web/images/ideal.png
  view/frontend/web/images/maestro.png
  view/frontend/web/images/masterpass.png
  view/frontend/web/images/paybybankapp.png
  view/frontend/web/images/paypal.png
  view/frontend/web/images/poipia.png
  view/frontend/web/images/ratepayinstall.png
  view/frontend/web/images/ratepayinvoice.png
  view/frontend/web/images/sepadirectdebit.png
  view/frontend/web/images/sofortbanking.png
  view/frontend/web/images/unionpayinternational.png
  view/frontend/web/template/payment/method-creditcard.html
  view/frontend/web/template/payment/method-default.html
  view/frontend/web/template/payment/method-giropay.html
  view/frontend/web/template/payment/method-ideal.html
  view/frontend/web/template/payment/method-ratepay.html
  view/frontend/web/template/payment/method-sepa.html
Labels: ready for merge

#416 Add change release version GitHub action
  .github/workflows/change-release-version.yml
Labels: no-release, ready for approval

#417 Tpwdcee 6288 a51try configuration
  .bin/crontab
  .bin/get-latest-shop-release-versions.sh
  .bin/install-magento.sh
  .bin/install-sampledata.sh
  .bin/new-shop-releases.txt
  .bin/remove-composer-lock-file.sh
  .bin/run-ui-tests.sh
  .bin/send-notify.sh
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .bin/update-shop-release-versions.sh
  .bin/upload-logs-and-notify.sh
  .env
  .travis.yml
  Dockerfile
  codeception.yml
  composer.json
  docker-compose.yml
  tests/_data/CardData.json
  tests/_data/CustomerData.json
  tests/_data/configure_payment_method_db.php
  tests/_data/crontab.xml
  tests/_data/gateway_configs/creditcard.json
  tests/_support/AcceptanceTester.php
  tests/_support/ActorExtendedWithWrappers.php
  tests/_support/Helper/Acceptance.php
  tests/_support/Helper/DbHelper.php
  tests/_support/Page/Base.php
  tests/_support/Page/Checkout.php
  tests/_support/Page/OrderReceived.php
  tests/_support/Page/Payment.php
  tests/_support/Page/Product3DS.php
  tests/_support/Page/ProductNon3DS.php
  tests/_support/Page/Verified.php
  tests/acceptance.suite.yml
  tests/acceptance/CreditCard3DSAuthorizeHappyPath.feature
  tests/acceptance/CreditCard3DSPurchaseHappyPath.feature
  tests/acceptance/CreditCardNon3DSPurchaseHappyPath.feature
Labels: no-release, ready for approval

#419 Add dependabot to PR lint
  .github/pr-labeler.yml
  .github/prlint.json
Labels: no-release

#420 Add github action to validate travis file
  .github/workflows/validate-travis-file.yml
Labels: no-release

#421 Use Wirecard GitHub actions and expand PR labeler
  .github/pr-labeler.yml
  .github/workflows/change-release-version.yml
  .github/workflows/run_cs_unit_coverage.yml
Labels: no-release
