Repository wirecard/magento2-ee, pull requests merged in 2020-01, with the labels that each got.

#348 Remove usage of ArrayInterface, update to OptionSourceInterface
  Gateway/Request/BasketFactory.php
  Model/Adminhtml/Source/PaymentAction.php
  Model/Adminhtml/Source/PoiPiaAction.php
  Model/Adminhtml/Support.php
  Model/Config/Backend/CreditCardConfig.php
  Test/Unit/Gateway/Request/BasketFactoryUTest.php
  view/frontend/templates/poipia.phtml
  view/frontend/templates/sepamandate.phtml
Labels: ready for review

#341 Tpwdcee 4803
  .gitignore
  Block/Adminhtml/System/Config/TestCredentials.php
  Block/Widget/TestCredentialsButton.php
  Controller/Frontend/Creditcard.php
  Gateway/Request/BasketFactory.php
  Model/Adminhtml/Source/PaymentAction.php
  Model/Adminhtml/Source/PoiPiaAction.php
  Model/Adminhtml/Support.php
  Model/Config/Backend/CreditCardConfig.php
  README.md
  Test/Unit/Gateway/Request/BasketFactoryUTest.php
  etc/adminhtml/system.xml
  etc/adminhtml/system/alipayxborder.xml
  etc/adminhtml/system/cc_vault.xml
  etc/adminhtml/system/credentials.xml
  etc/adminhtml/system/creditcard.xml
  etc/adminhtml/system/giropay.xml
  etc/adminhtml/system/ideal.xml
  etc/adminhtml/system/paybybankapp.xml
  etc/adminhtml/system/paypal.xml
  etc/adminhtml/system/poi_pia.xml
  etc/adminhtml/system/ratepayinvoice.xml
  etc/adminhtml/system/sepacredit.xml
  etc/adminhtml/system/sepadirectdebit.xml
  etc/adminhtml/system/sofortbanking.xml
  i18n/de_DE.csv
  i18n/en_US.csv
  i18n/fr_FR.csv
  i18n/id_ID.csv
  i18n/ja_JP.csv
  i18n/ko_KR.csv
  i18n/pl_PL.csv
  i18n/zh_Hans_CN.csv
  i18n/zh_Hant_TW.csv
  view/adminhtml/templates/system/config/form/test_credentials_button.phtml
  view/adminhtml/templates/system/config/test_credentials.phtml
  view/frontend/templates/poipia.phtml
  view/frontend/templates/sepamandate.phtml
Labels: approval required, ready for approval

#343 Change release process configuration
  .bin/check-release-notes-exist.sh
  .bin/generate-readme-badge.sh
  .bin/generate-tag.sh
  .bin/generate-wiki-notes.sh
  .bin/version-helper.php
  .github/pr-labeler.yml
  .github/workflows/create_release.yml
  .github/workflows/label_pull_request.yml
  .travis.yml
  CHANGELOG.md
  composer.json
Labels: no-release

#347 Add QuoteAddress object to addressfactory and accountholderfactory
  Controller/Frontend/Callback.php
  Controller/Frontend/Creditcard.php
  Gateway/Helper/ThreeDsHelper.php
  Gateway/Request/AccountHolderFactory.php
  Gateway/Request/AddressFactory.php
  Gateway/Request/CreditCardTransactionFactory.php
  Gateway/Validator/AddressValidatorFactory.php
  Test/Unit/Controller/Frontend/CreditcardTest.php
  Test/Unit/Gateway/Request/AccountHolderFactoryUTest.php
  Test/Unit/Gateway/Request/AddressFactoryUTest.php
  Test/Unit/Gateway/Validator/AddressValidatorFactoryUTest.php
  etc/di.xml
Labels: ready for merge

#355 Remove double quotes from Travis global variables
  .travis.yml
Labels: no-release
