Repository wirecard/magento2-ee, pull requests merged in 2020-05, with the labels that each got.

#423 Remove SHOPVERSIONS and add compose dry run for unit tests
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  SHOPVERSIONS
Labels: no-release

#424 Update 'validate travis' pipeline to run only on travis file change
  .github/workflows/validate-travis-file.yml
Labels: no-release

#425 Remove incrementation with one month of cc expiration date
  Gateway/Model/Notify.php
Labels: ready for merge

#429 Adapt travis file UI tests
  .bin/compatible-shop-releases.txt
  .bin/start-shopsystem.sh
  .travis.yml
Labels: no-release, ready for review

#436 Tpwdcee 6874 feature
  Gateway/Helper/AccountHolderMapper.php
  composer.json
Labels: ready for review
