Repository wirecard/magento2-ee, pull requests merged in 2020-08, with the labels that each got.

#465 Check amount handling after credit card form is rendered
  Controller/Frontend/CreditCardOrderValidation.php
  Test/Unit/Block/Adminhtml/Support/ContactUTest.php
  Test/Unit/Controller/Frontend/CreditCardOrderValidationUTest.php
  Test/bootstrap.php
  view/frontend/web/js/view/payment/method-renderer/constants.js
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
Labels: ready for review

#463 RC-3.1.6-patch
  CHANGELOG.md
  Controller/Frontend/CreditCardOrderValidation.php
  README.md
  Test/Unit/Block/Adminhtml/Support/ContactUTest.php
  Test/Unit/Controller/Frontend/CreditCardOrderValidationUTest.php
  Test/bootstrap.php
  composer.json
  etc/module.xml
  view/frontend/web/js/view/payment/method-renderer/constants.js
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
Labels: patch

#467 Update compatible-shop-releases.txt
  .bin/compatible-shop-releases.txt
Labels: no-release

#464 create wirecard cron group
  etc/cron_groups.xml
  etc/crontab.xml
Labels: ready for review

#468 Validate branch name
  .github/pr_lint.json
  .github/prlint.json
  .github/workflows/pr-lint.yml
Labels: no-release

#469 Rc 3.1.7 patch
  .bin/compatible-shop-releases.txt
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  CHANGELOG.md
  Test/Unit/Model/SupportUTest.php
  etc/cron_groups.xml
  etc/crontab.xml
  etc/module.xml
Labels: patch
