Repository wirecard/magento2-ee, pull requests merged in 2020-03, with the labels that each got.

#382 Update README badge
  CHANGELOG.md
  README.md
  SHOPVERSIONS
Labels: no-release

#384 Remove auto shop version update
  .travis.yml
Labels: no-release

#389 Delete invalid attribute "name" from credentials.xml.
  etc/adminhtml/system/credentials.xml
Labels: ready for review

#386 Tpwdcee 6259 feature
  Gateway/Command/WirecardCommand.php
  Gateway/Request/CreditCardTransactionFactory.php
  view/frontend/web/js/view/payment/method-renderer/vault.js
Labels: ready for test

#390 Rc 3.1.1 patch
  CHANGELOG.md
  Gateway/Command/WirecardCommand.php
  Gateway/Request/CreditCardTransactionFactory.php
  SHOPVERSIONS
  etc/module.xml
  view/frontend/web/js/view/payment/method-renderer/vault.js
Labels: patch

#387 Add showing error message from response
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
  view/frontend/web/template/payment/method-vault.html
Labels: ready for approval

#391 Refactoring of the PHP code for Credit Card
  Block/Checkout/CreditCardThreeDForm.php
  Controller/Frontend/Callback.php
  Gateway/Response/ResponseHandler.php
  composer.json
  view/frontend/layout/wirecard_elasticengine_frontend_callback.xml
  view/frontend/layout/wirecard_elasticengine_frontend_sepamandate.xml
  view/frontend/templates/creditcardthreedform.phtml
Labels: ready for review

#395 Change setup-php checkout version
  .github/workflows/run_cs_unit_coverage.yml
Labels: no-release

#396 TPWDCEE-6329.
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
Labels: ready for merge

#398 Tpwdcee 6347 feature
  Controller/Frontend/Callback.php
  Controller/Frontend/Redirect.php
  Gateway/Response/ResponseHandler.php
  Test/Unit/Controller/Frontend/RedirectTest.php
  Test/Unit/Gateway/Response/ResponseHandlerUTest.php
  Test/Unit/Model/Ui/TokenUiComponentProviderUTest.php
  _TERMS_OF_USE
Labels: ready for review
