Repository wirecard/magento2-ee, pull requests merged in 2020-07, with the labels that each got.

#446 Reinitialize CC form after coupon apply/cancel
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
Labels: ready for merge

#448 Update error handler to use proper context
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
Labels: ready for merge

#451 Tpwdcee 7150 feature
  composer.json
Labels: ready for merge

#453 add changelog for 3.1.4
  CHANGELOG.md
Labels: patch

#454 Increase unit tests support and update magento community version
  .github/workflows/run_cs_unit_coverage.yml
  Model/Ui/TokenUiComponentProvider.php
  README.md
  composer.json
Labels: no-release

#455 Add extension version to composer.json file
  composer.json
Labels: no-release

#458 TPWDCEE-6558 Building forms in PHP
  .github/workflows/run_cs_unit_coverage.yml
  Block/Checkout/CreditCardThreeDForm.php
  Block/Checkout/FormFields.php
  Block/Checkout/SepaMandateBlock.php
  Controller/Frontend/Callback.php
  Controller/Frontend/Redirect.php
  Gateway/Config/CanCaptureHandler.php
  Gateway/Config/CanVoidHandler.php
  Model/Adminhtml/Support.php
  Test/Unit/Block/Checkout/SepaMandateBlockUTest.php
  Test/Unit/Gateway/Config/CanCaptureHandlerTest.php
  Test/Unit/Gateway/Config/CanVoidHandlerUTest.php
  view/frontend/layout/wirecard_elasticengine_frontend_callback.xml
  view/frontend/templates/formfields.phtml
  view/frontend/templates/sepamandate.phtml
  view/frontend/web/css/main.css
  view/frontend/web/js/validator/min-age-validator.js
  view/frontend/web/js/view/payment/method-renderer/default.js
  view/frontend/web/js/view/payment/method-renderer/ratepay.js
Labels: ready for approval

#460 fix IE 11 commpatibility with javascript
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
Labels: no-release, ready for merge

#461 Tpwdcee 7347 Send Email on Invoice creation
  Gateway/Model/Notify.php
  Test/Unit/Gateway/Model/NotifyUTest.php
Labels: no-release, ready for review

#457 3.1.5 patch version
  .github/workflows/run_cs_unit_coverage.yml
  Block/Checkout/CreditCardThreeDForm.php
  Block/Checkout/FormFields.php
  Block/Checkout/SepaMandateBlock.php
  CHANGELOG.md
  Controller/Frontend/Callback.php
  Controller/Frontend/Redirect.php
  Gateway/Config/CanCaptureHandler.php
  Gateway/Config/CanVoidHandler.php
  Gateway/Model/Notify.php
  Model/Adminhtml/Support.php
  Test/Unit/Block/Checkout/SepaMandateBlockUTest.php
  Test/Unit/Gateway/Config/CanCaptureHandlerTest.php
  Test/Unit/Gateway/Config/CanVoidHandlerUTest.php
  Test/Unit/Gateway/Model/NotifyUTest.php
  composer.json
  etc/adminhtml/system.xml
  etc/module.xml
  i18n/fr_FR.csv
  view/frontend/layout/wirecard_elasticengine_frontend_callback.xml
  view/frontend/templates/formfields.phtml
  view/frontend/templates/sepamandate.phtml
  view/frontend/web/css/main.css
  view/frontend/web/js/validator/min-age-validator.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/default.js
  view/frontend/web/js/view/payment/method-renderer/ratepay.js
  view/frontend/web/js/view/payment/method-renderer/seamlessformutils.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
Labels: patch
