Repository wirecard/magento2-ee, pull requests merged in 2020-02, with the labels that each got.

#362 Switch Unit Tests from Travis to GitHub Actions
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
Labels: no-release, ready for approval

#365 Add feature option to PR Lint
  .github/prlint.json
Labels: no-release

#366 Tpwdcee 5977 feature
  Model/Adminhtml/Support.php
  SHOPVERSIONS
  Test/Unit/Model/SupportUTest.php
  etc/crontab.xml
  etc/module.xml
  view/adminhtml/email/contact_support_email.html
Labels: ready for merge

#369 Disable nightly compatibility checks
  .travis.yml
Labels: no-release, ready for approval

#367 Rc 3.0.1 patch
  CHANGELOG.md
  Model/Adminhtml/Support.php
  SHOPVERSIONS
  Test/Unit/Model/SupportUTest.php
  etc/crontab.xml
  etc/module.xml
  view/adminhtml/email/contact_support_email.html
Labels: patch

#371 Remove unrelevant badges
  README.md
Labels: no-release

#368 Tpwdcee 5860 feature Update to payment SDK 4.0.1, fix dependency on php-enum
  composer.json
Labels: ready for test

#373 Tpwdcee 5915 feature update php unitversion
  Test/Unit/Block/Checkout/PoiPiaBlockUTest.php
  Test/Unit/Block/Checkout/SepaMandateBlockUTest.php
  Test/Unit/Block/Customer/CardRendererUTest.php
  Test/Unit/Controller/Adminhtml/Support/ContactUTest.php
  Test/Unit/Controller/Adminhtml/Test/CredentialsTest.php
  Test/Unit/Controller/Frontend/CancelTest.php
  Test/Unit/Controller/Frontend/NotifyTest.php
  Test/Unit/Controller/Frontend/RedirectTest.php
  Test/Unit/Controller/Frontend/SepamandateUTest.php
  Test/Unit/Gateway/Command/WirecardCaptureCommandUTest.php
  Test/Unit/Gateway/Command/WirecardCommandUTest.php
  Test/Unit/Gateway/Command/WirecardRefundCommandUTest.php
  Test/Unit/Gateway/Command/WirecardVoidCommandUTest.php
  Test/Unit/Gateway/Config/PaymentSdkConfigFactoryUTest.php
  Test/Unit/Gateway/Helper/OrderUTest.php
  Test/Unit/Gateway/Model/NotifyUTest.php
  Test/Unit/Gateway/Model/RetrieveTransactionUTest.php
  Test/Unit/Gateway/Model/TransactionUpdaterUTest.php
  Test/Unit/Gateway/Request/TransactionFactoryUTest.php
  Test/Unit/Gateway/Response/ResponseHandlerUTest.php
  Test/Unit/Gateway/Service/TransactionServiceFactoryUTest.php
  Test/Unit/Model/Ui/ConfigProviderUTest.php
  Test/Unit/Observer/CreditCardDataAssignObserverUTest.php
  Test/Unit/Observer/IdealDataAssignObserverUTest.php
  composer.json
Labels: ready for merge

#379 Change release name and add emtpy space
  .github/workflows/create_release.yml
Labels: no-release

#378 Update downwards comp for paymenttokens
  Gateway/Model/Notify.php
  Model/Ui/TokenUiComponentProvider.php
  view/frontend/web/template/payment/method-default.html
Labels: ready for review

#376 Tpwdcee 5836 my favourite payment
  Controller/Frontend/Creditcard.php
  Gateway/Model/Notify.php
  Model/Ui/ConfigProvider.php
  Model/Ui/TokenUiComponentProvider.php
  Test/Unit/Controller/Frontend/CreditcardTest.php
  Test/Unit/Gateway/Model/NotifyUTest.php
  Test/Unit/Model/Ui/TokenUiComponentProviderUTest.php
  composer.json
  view/frontend/web/js/view/payment/method-renderer.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
  view/frontend/web/template/payment/method-vault.html
Labels: approval required, ready for approval

#377 Fix release polling script for whitelabelling triggering
  .bin/check-release-notes-exist.sh
Labels: no-release

#363 RC 3.1.0
  .bin/phraseapp/wd-phraseapp.rb
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  CHANGELOG.md
  Controller/Frontend/Creditcard.php
  Gateway/Model/Notify.php
  Gateway/Model/TransactionUpdater.php
  Model/Ui/ConfigProvider.php
  Model/Ui/TokenUiComponentProvider.php
  SHOPVERSIONS
  Test/Unit/Block/Checkout/PoiPiaBlockUTest.php
  Test/Unit/Block/Checkout/SepaMandateBlockUTest.php
  Test/Unit/Block/Customer/CardRendererUTest.php
  Test/Unit/Controller/Adminhtml/Support/ContactUTest.php
  Test/Unit/Controller/Adminhtml/Test/CredentialsTest.php
  Test/Unit/Controller/Frontend/CancelTest.php
  Test/Unit/Controller/Frontend/CreditcardTest.php
  Test/Unit/Controller/Frontend/NotifyTest.php
  Test/Unit/Controller/Frontend/RedirectTest.php
  Test/Unit/Controller/Frontend/SepamandateUTest.php
  Test/Unit/Gateway/Command/WirecardCaptureCommandUTest.php
  Test/Unit/Gateway/Command/WirecardCommandUTest.php
  Test/Unit/Gateway/Command/WirecardRefundCommandUTest.php
  Test/Unit/Gateway/Command/WirecardVoidCommandUTest.php
  Test/Unit/Gateway/Config/PaymentSdkConfigFactoryUTest.php
  Test/Unit/Gateway/Helper/OrderUTest.php
  Test/Unit/Gateway/Model/NotifyUTest.php
  Test/Unit/Gateway/Model/RetrieveTransactionUTest.php
  Test/Unit/Gateway/Model/TransactionUpdaterUTest.php
  Test/Unit/Gateway/Request/TransactionFactoryUTest.php
  Test/Unit/Gateway/Response/ResponseHandlerUTest.php
  Test/Unit/Gateway/Service/TransactionServiceFactoryUTest.php
  Test/Unit/Model/Ui/ConfigProviderUTest.php
  Test/Unit/Model/Ui/TokenUiComponentProviderUTest.php
  Test/Unit/Observer/CreditCardDataAssignObserverUTest.php
  Test/Unit/Observer/IdealDataAssignObserverUTest.php
  composer.json
  etc/adminhtml/system/alipayxborder.xml
  etc/adminhtml/system/cc_vault.xml
  etc/adminhtml/system/creditcard.xml
  etc/di.xml
  etc/module.xml
  i18n/de_DE.csv
  i18n/en_US.csv
  i18n/fr_FR.csv
  i18n/id_ID.csv
  i18n/ja_JP.csv
  i18n/ko_KR.csv
  i18n/pl_PL.csv
  i18n/zh_Hans_CN.csv
  i18n/zh_Hant_TW.csv
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/view/payment/method-renderer.js
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/vault.js
  view/frontend/web/template/payment/method-vault.html
Labels: minor

#380 Remove Unit tests from Travis CI
  .travis.yml
Labels: no-release, ready for merge
